version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=bvonpotobsky
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5434:5434
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
